[package]
name = "math"
version = "0.1.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# itertools = "0.10.1"
nalgebra = "0.29.0"
num_cpus = "1.13.0"
ordered-float = "2.8.0"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
rand = "0.8.4"
rayon = "1.5.0"
serde = { version = "1.0.120", features = ["derive"] }

[build-dependencies]
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.56"

[profile.dev]
opt-level = 3
panic='abort'
debug=true

[profile.test]
opt-level = 0
