[package]
name = "math"
version = "2.2.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2024"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# itertools = "0.10.1"
num-traits = "~0.2"
num_cpus = "~1"
ordered-float = "~5.3"
rand = { version = "~0.10.1", features = ["thread_rng"] }
rayon = "~1.12"
serde = { version = "~1.0", features = ["derive"], optional = true }
deepsize = { version = "~0.2", optional = true }
typenum = "1.20.1"
thermite = { git = "https://github.com/raygon-renderer/thermite" }

[dev-dependencies]
proptest = "1.10.0"

[build-dependencies]
serde_json = { version = "~1.0" }
serde = { version = "~1.0", features = ["derive"], optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]
deepsize = ["dep:deepsize"]
