[package]
name = "math"
version = "0.3.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# itertools = "0.10.1"
nalgebra = "0.31.0"
num_cpus = "1.13.0"
ordered-float = "3.0.0"
packed_simd = { version = "0.3.8", package = "packed_simd_2" }
rand = "0.8.5"
rayon = "1.5.3"
serde = { version = "1.0.137", features = ["derive"] }


[build-dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"

[profile.dev]
opt-level = 3
panic='abort'
debug=true

[profile.test]
opt-level = 0
